--
-- PostgreSQL database dump
--

-- Dumped from database version 14.16 (Homebrew)
-- Dumped by pg_dump version 14.16 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: gavinreid
--

COPY public.alembic_version (version_num) FROM stdin;
2f11d6b8ca1a
\.


--
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: gavinreid
--

COPY public.tasks (id, name, type, is_free, price, main_prompt, bullet_points, image_path, description) FROM stdin;
23	Billing Distribution 2015	writing_task_1_report	t	\N	The pie chart shows the billing distribution among five buildings for the month of August 2015.	\N	images/writing_task_1_report/billing_distribution_2015.png	This pie chart shows the billing distribution among five different buildings (A, B, C, D, and E). Building A has the highest share at 24.3%, followed by Building C at 22% and Building E at 20.1%. Building D and Building B have 16.4% and 17.2%, respectively. The chart provides a clear visual representation of how costs were distributed across these buildings during the specified month.
24	Carbon Dioxide Emissions Japan	writing_task_1_report	t	\N	The bar chart shows the total CO₂ emissions in Japan over a five-year period from 2008 to 2012.	\N	images/writing_task_1_report/carbon_dioxide_emmisions_japan.png	This bar chart displays Japan's CO₂ emissions over a five-year period from 2008 to 2012 in kg/kWh. The emissions remained relatively high from 2008 to 2010, showing a stable trend. A noticeable decline can be seen in 2011 and 2012, indicating efforts to reduce carbon output. The highest emissions occurred around 2010, while the lowest was in 2012.
14	School Uniforms Policy	writing_task_2	t	\N	In many countries, it is mandatory for school children to wear uniforms. Do the advantages of this policy outweigh the disadvantages? Give reasons for your answer and include any relevant examples from your own knowledge or experience.	\N	\N	\N
15	Museum Admission Fees	writing_task_2	t	\N	Many museums charge for admission while others are free. Do you think the advantages of charging people for admission outweigh the disadvantages?	\N	\N	\N
16	Importance of Ambition	writing_task_2	t	\N	Ambition is a positive quality for people to have in society today. How important is it for people who want to succeed in life? Is it a positive or negative characteristic?	\N	\N	\N
17	Transportation and Pollution	writing_task_2	t	\N	Research has shown that the transportation of products and people are the main source of pollution. Some people believe the government should be in charge of this, while others believe it is the fault of individuals. Discuss both views and give your opinion. Give reasons for your answer and include relevant examples from your knowledge or experience.	\N	\N	\N
1	House Sitting	writing_task_1_letter	t	\N	You are going on holiday and a friend has agreed to look after your house and pet. Write a letter to your friend.	give contact details for when you are away, give instructions about how to care for your pet, describe other household duties you would like your friend to undertake	\N	\N
6	Invitation to a Party	writing_task_1_letter	t	\N	Write an informal invitation letter to a friend inviting them to a party.	State the date and time, provide the venue, include any instructions for the guest	\N	\N
8	Thank You Note	writing_task_1_letter	t	\N	Write a thank-you letter to a friend for a recent gift they gave you.	Express gratitude, describe the gift, mention how you will use it	\N	\N
10	Apology for a Missed Appointment	writing_task_1_letter	t	\N	Write an apology letter for missing an appointment with a colleague.	Explain the reason for missing the appointment, apologize, offer to reschedule	\N	\N
2	Travel to a New Country	writing_task_1_letter	f	5	You have just moved to a new country. Write a letter to your friend describing your new home and your experiences so far.	Describe your home, explain the culture, discuss what you like and dislike	\N	\N
3	A Job Application	writing_task_1_letter	f	5	You are applying for a job in a company abroad. Write a letter to the company explaining why you are interested in the job.	State your skills, explain your interest in the company, mention how you meet the job criteria	\N	\N
4	A Formal Complaint	writing_task_1_letter	f	5	Write a formal letter of complaint to a company about a product you bought and were dissatisfied with.	Describe the product, explain the issue, state how the company can resolve it	\N	\N
5	A Request for Information	writing_task_1_letter	f	5	Write a letter to a travel agency requesting information about a holiday package.	Ask about prices, explain your preferred dates, request further details about the package	\N	\N
7	Advice for a Friend	writing_task_1_letter	f	5	Write a letter to a friend offering advice on how to handle a stressful situation.	Explain how to relax, suggest activities to reduce stress, offer emotional support	\N	\N
9	Job Reference	writing_task_1_letter	f	5	Write a reference letter for a colleague applying for a new job.	Describe their strengths, explain why they are suitable for the role, provide your contact details	\N	\N
18	Extreme Sports and Safety	writing_task_2	f	5	Extreme sports such as skydiving and rock climbing are very dangerous and should be banned. To what extent do you agree or disagree with this view?	\N	\N	\N
19	Personal Information Online	writing_task_2	f	5	These days more people put their personal information, such as names, addresses and telephone numbers, online for everyday activities such as socialising on social networks or banking purposes. Do you think it is a positive or negative development?	\N	\N	\N
20	Young Leaders in Business	writing_task_2	f	5	The leaders or directors of organizations are often older people. But some people say that young people can also be a leader. Do you agree or disagree?	\N	\N	\N
21	Standard of Living Today	writing_task_2	f	5	Some people believe that people living in the twenty-first century have a better standard of living as compared to previous centuries. To what extent do you agree or disagree with this statement? Give reasons for your answer and include relevant examples from your knowledge or experience.	\N	\N	\N
22	Crime and Its Causes	writing_task_2	f	5	A portion of the human population believes that criminal behaviour has its roots in genes. Others think that circumstances lead people to commit crimes. Discuss your take on both views and put forward your opinions.	\N	\N	\N
12	Recycled Materials Proportions (1982-2010)	writing_task_1_report	t	\N	This graph shows the proportion of four different materials that were recycled from 1982 to 2010 in a particular country.	\N	images/writing_task_1_report/recycled_materials.png	This line graph shows the recycling rate trends for four materials over a 28-year period. Paper & cardboard consistently had the highest recycling rates, peaking around 80%. Glass containers fluctuated but remained around 50%. Aluminium cans saw a steady increase, while plastics had the lowest recycling rate, though it improved over time. The chart highlights the progress in recycling efforts across different materials.
13	Population of India and China (2000-2050)	writing_task_1_report	f	5	The graph below shows the population of India and China from the year 2000 to the present day with projections for growth to the year 2050.	\N	images/writing_task_1_report/population_india_china.png	This line graph tracks the projected population changes for India and China over 50 years. China's population starts higher than India's in 2000, but growth slows and begins to decline around 2040. India's population shows continuous growth, eventually surpassing China by 2050. The graph effectively illustrates the shifting demographics and projected trends in population growth.
25	Coastline by Country	writing_task_1_report	t	\N	The bar chart compares the total coastline coverage (in km) for five different countries.	\N	images/writing_task_1_report/coastline_by_country.png	This bar graph compares the total coastline length (in km) for five countries. Canada has the longest coastline, exceeding 90,000 km, followed by Indonesia and Russia. The Philippines and Japan have significantly shorter coastlines in comparison. The chart emphasizes the vast differences in coastline coverage, with Canada standing out as an outlier.
26	Hazardous Waste Inventory 2014	writing_task_1_report	t	\N	The bar chart shows the amount of different types of hazardous waste recorded in 2014.	\N	images/writing_task_1_report/hazardous_waste_inventory_2014.png	This bar chart presents data on hazardous waste inventory in kilograms for different waste types. Hydraulic used diesel fuel has the highest amount, followed by busted fluorescent lamps and wet batteries. Medical waste and expired medicine contribute the least. The graph highlights the major contributors to hazardous waste in the given year.
27	Active Military Manpower Per Country	writing_task_1_report	t	\N	The step chart displays the number of active military personnel in five different countries.	\N	images/writing_task_1_report/military_manpower.png	This step chart compares the active military manpower of five countries: China, the US, India, Russia, and North Korea. China has the largest military force, with over 2.4 million personnel, followed by the US and India. Russia and North Korea have smaller military forces but still a significant presence. The visual representation shows a clear hierarchical structure in global military manpower.
28	Toyota Car Sales - Quarterly Monitoring	writing_task_1_report	t	\N	The bar chart presents Toyota’s quarterly car sales from January 2014 to October 2015.	\N	images/writing_task_1_report/toyota_car_sales.png	This bar chart presents Toyota’s quarterly car sales from January 2014 to October 2015. Sales fluctuated, with peaks in April and October 2014 and 2015. A drastic drop occurred in October 2015, possibly due to external market factors. The chart visually depicts the seasonal nature of car sales and trends over time.
29	Thermal Conductivity of Materials	writing_task_1_report	t	\N	The line graph compares the thermal conductivity (W/m·K) of various materials at 25°C.	\N	images/writing_task_1_report/thermal_conductivity_material.png	This line graph compares the thermal conductivity (W/m·K) of different materials at 25°C. Acetone has the highest thermal conductivity, followed by Acetals and Acetylene gas. Acrylic and atmospheric air have the lowest values. The graph provides insight into the thermal properties of various materials for engineering and scientific applications.
30	2014 World Food Consumption	writing_task_1_report	t	\N	The pie chart represents the percentage share of different food categories consumed globally in 2014.	\N	images/writing_task_1_report/world_food_consumption.png	This pie chart represents the percentage share of different food categories consumed globally in 2014. Meat had the highest consumption at 31.4%, followed by fish (27.9%). Cereals, vegetables, and fruits had similar shares, each around 10-12%. Rice and bread had the smallest shares at 2.5% and 5.5%, respectively. The chart highlights global dietary habits and the dominance of meat and fish in consumption patterns.
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: gavinreid
--

COPY public.users (id, email, password_hash, is_verified, verification_token, token_expiration) FROM stdin;
1	gavinjohnreid@gmail.com	scrypt:32768:8:1$dzQwio26IrCEDeLz$08c963028a47d324da1f75dec0a48abfa005affa0df3561dc59b7f7588fcc127d5750937fedd28f692e483153ee37f6a1ad74e8cbb5e7c58b88489b380e423c0	t	\N	\N
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: gavinreid
--

COPY public.payments (id, user_id, task_id, amount_paid, payment_status) FROM stdin;
\.


--
-- Data for Name: transcripts; Type: TABLE DATA; Schema: public; Owner: gavinreid
--

COPY public.transcripts (id, user_id, task_id, transcription, feedback, created_at) FROM stdin;
3	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"task_achievement": "The candidate addresses the prompt appropriately and provides adequate information, though certain details could be further elaborated.", "coherence_cohesion": "The text is logically structured and cohesive, but could benefit from more sophisticated transitions and connective phrases.", "lexical_resource": "The vocabulary used is adequate, but could be more varied and precise in certain areas.", "grammatical_range_accuracy": "There are several grammar and punctuation errors that affect overall clarity. The candidate uses a limited range of sentence structures.", "band_scores": {"task_achievement": 6.0, "coherence_cohesion": 6.0, "lexical_resource": 5.5, "grammatical_range_accuracy": 5.0, "overall_band": 5.6}, "improved_response": "Dear Richard,\\n\\nI trust this letter finds you in good health. I am writing to express my sincere gratitude for agreeing to look after my house and pet while I am on holiday. Your assistance is greatly appreciated.\\n\\nShould you need to reach me during my absence, I can be contacted at +44 7123 456789 or via email at john.smith@email.com. Rest assured, I will be checking my messages intermittently.\\n\\nWith regards to taking care of my dog, I kindly request that you feed her twice daily, once in the morning and once at night. You will find her food stored in the kitchen. Additionally, please ensure she gets a brief walk every evening and that she has access to fresh water at all times.\\n\\nAs for the plants located in the living room and on the balcony, they require watering on a weekly basis.\\n\\nOnce again, thank you for your invaluable help. As a small token of my appreciation, I will bring back a little souvenir from my travels.\\n\\nLooking forward to seeing you soon,\\n\\nGavin", "did_well": [], "could_improve": []}	2025-02-22 09:19:26.841876
4	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"task_achievement": "The response addresses the task with some errors. The candidate provides instructions for taking care of the house and pet, but no information about the house security system, which the prompt requires.", "coherence_cohesion": "The structure is largely logical. The ideas are organised, but there is room for improvement in paragraphing. Cohesive devices are lacking.", "lexical_resource": "The candidate uses a limited range of vocabulary which is not always accurate or appropriate.", "grammatical_range_accuracy": "The candidate's sentences are generally simple in structure. There are several grammatical errors and incorrect verb forms.", "band_scores": {"task_achievement": 5.5, "coherence_cohesion": 6.0, "lexical_resource": 5.5, "grammatical_range_accuracy": 5.0, "overall_band": 5.5}, "improved_response": "Dear Richard,\\\\n\\\\nI trust this finds you well. I am writing to extend my heartfelt thanks for agreeing to look after my home and pet while I am away on holiday. Your help is greatly appreciated.\\\\n\\\\nShould you need to reach me for any reason, please feel free to contact me at any time on +44 7123 456789 or via email at john.smith@email.com. I will endeavour to check my messages as frequently as possible.\\\\n\\\\nWith regards to caring for my dog, she needs to be fed twice daily, once in the morning and once at night. Her food can be found in the kitchen. Additionally, she requires a brief walk every evening for exercise. Please ensure she has access to fresh water at all times.\\\\n\\\\nI also have some plants in the living room and on the balcony that will need watering once a week.\\\\n\\\\nFurthermore, please ensure that the house security system is activated every night for safety reasons.\\\\n\\\\nThank you once again for your invaluable assistance. I look forward to showing my appreciation with a small token from my travels.\\\\n\\\\nBest regards,\\\\nGavin", "did_well": [], "could_improve": []}	2025-02-22 09:34:55.780155
5	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:38:25.118063
6	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:38:50.904717
7	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:39:52.433397
8	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:40:34.051829
9	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"task_achievement": "The candidate has addressed the task requirements to some extent. The basic information about taking care of the house, pet, and plants has been given. However, the points are not fully developed and some details might be needed for more clarity.", "coherence_cohesion": "The candidate uses simple linking words, but there is a lack of clear paragraphing and logical organization. The points are somewhat isolated rather than being coherently linked.", "lexical_resource": "The candidate uses a limited range of vocabulary which is repetitive and lacks precision. The words and phrases used are very basic and simplistic.", "grammatical_range_accuracy": "The candidate makes many grammatical errors and sentence structures are limited and repetitive. There is misuse of articles and prepositions, and tense usage is inconsistent.", "band_scores": {"task_achievement": 5.0, "coherence_cohesion": 4.0, "lexical_resource": 4.0, "grammatical_range_accuracy": 4.0, "overall_band": 4.3}, "improved_response": "Dear Richard,\\\\n\\\\nI hope this message finds you well. I am writing to express my gratitude for your willingness to look after my house and pet while I am away on holiday. Your assistance is highly appreciated.\\\\n\\\\nShould you need to get in touch with me during my absence, you can reach me on my mobile number, +44 7123 456789, or alternatively, you can drop me an email at john.smith@email.com. I will make an effort to check my messages as often as possible.\\\\n\\\\nAs for my dog, she requires feeding twice a day, once in the morning and once at night. You will find her food stored in the kitchen. Additionally, she needs a brief walk every night for exercise. Please ensure that she has access to fresh water at all times.\\\\n\\\\nRegarding the plants, there are some in the living room and others on the balcony. They need to be watered once a week to ensure they remain healthy.\\\\n\\\\nThank you once again for your help. As a token of my gratitude, I will bring you a small gift from my trip.\\\\n\\\\nLook forward to seeing you soon,\\\\nGavin", "did_well": [], "could_improve": []}	2025-02-22 09:41:12.542419
10	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:47:27.524499
11	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"task_achievement": "The response adequately addresses the prompt, detailing the care required for the house and pet. However, some points lack detail and could be further extended.", "coherence_cohesion": "The general flow of ideas is logical, but the paragraphing is inconsistent and cohesive devices are not used effectively.", "lexical_resource": "The vocabulary used is limited and repetitious, with some inappropriate word choices.", "grammatical_range_accuracy": "There are several grammatical errors and the sentence structures are simple and repetitive.", "band_scores": {"task_achievement": 6.0, "coherence_cohesion": 5.5, "lexical_resource": 5.0, "grammatical_range_accuracy": 5.0, "overall_band": 5.4}, "improved_response": "Dear Richard,\\n\\nI hope this letter finds you in good health. I'm writing to express my gratitude for your willingness to look after my house and pet while I'm away on holiday.\\n\\nIn case of any queries or emergencies, you can reach me at +44 7123 456789, or drop me an email at john.smith@email.com. I'll make sure to check my messages periodically.\\n\\nRegarding my dog, it's necessary to feed her twice a day, once in the morning and again at night. You'll find her food in the kitchen. Additionally, she enjoys a brief stroll every night. Please ensure she always has fresh water available.\\n\\nI also have some plants in the living room and on the balcony that require watering once a week.\\n\\nThank you once again for your assistance! I look forward to bringing you a small token of appreciation from my trip.\\n\\nBest regards,\\nGavin", "did_well": [], "could_improve": []}	2025-02-22 09:48:56.999219
12	1	6	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:50:52.850244
13	1	6	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 09:53:28.832691
14	1	6	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"task_achievement": "The candidate's response sufficiently addresses the prompt. The candidate provides information about the dog and plants that need care, and also provides contact details. However, there's room for extending the points by mentioning more about the house, such as any security measures or other tasks that need to be performed.", "coherence_cohesion": "The response has a clear structure, but it lacks proper transitions between ideas, which can make the message seem disjointed. The candidate could improve the flow by using more cohesive devices.", "lexical_resource": "The candidate's vocabulary is adequate but limited. There are few variations in word choice or complexity, which could be increased to enhance the response.", "grammatical_range_accuracy": "There are several grammatical errors and omissions in the response. Sentences are simple and lack complexity, while some key grammatical structures are missing. Prepositions and verb tenses are often incorrectly used.", "band_scores": {"task_achievement": 6.0, "coherence_cohesion": 5.0, "lexical_resource": 5.0, "grammatical_range_accuracy": 4.0, "overall_band": 5.0}, "improved_response": "Dear Richard,\\n\\nI trust this message finds you well. I wanted to express my gratitude for your willingness to look after my house and pet while I am on holiday. Your help is truly appreciated.\\n\\nShould you need to contact me during my absence, please feel free to call me on +44 7123 456789 or send an email to john.smith@email.com. I will make an effort to check my messages whenever possible.\\n\\nWith regard to my dog, I kindly ask that you feed her twice a day, once in the morning and once in the evening. You can find her food stored in the kitchen. Additionally, she requires a brief walk each night. Please ensure she has access to fresh water at all times.\\n\\nI also have several plants located in the living room and on the balcony that require watering once a week.\\n\\nThank you once again for your invaluable assistance. I will be sure to bring you a small token of appreciation from my trip.\\n\\nBest wishes,\\nGavin", "did_well": [], "could_improve": []}	2025-02-22 09:54:00.071492
15	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 12:00:32.126748
16	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 12:02:12.99833
17	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 12:03:17.037439
18	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 12:04:08.430897
19	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 12:05:16.415662
20	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 12:13:26.448464
21	1	12	The graph illustrates the recycling rates of four materials — paper & cardboard, glass containers, aluminium cans, and plastics — from 1982 to 2010.\n\nPaper and cardboard had the highest recycling rates, starting at around 50% in 1982 and steadily increasing to nearly 80% by 2010. Glass containers saw a similar upward trend, beginning at approximately 40% and rising to 70% over the same period, reflecting significant progress.\n\nAluminium cans experienced a gradual rise in recycling rates, from about 10% in 1982 to just over 60% by 2010. Plastics, however, lagged behind with the lowest recycling rates. In 1982, only about 5% of plastics were recycled, and although this increased slightly each year, by 2010, only 10% of plastics were being recycled.\n\nOverall, while all materials saw improvements in recycling rates, paper and cardboard consistently led, with plastics making the slowest progress.	{"task_achievement": "The candidate accurately addressed the task, included all key features, and made relevant comparisons. The candidate effectively summarized the data and provided an appropriate overview.", "coherence_cohesion": "The candidate demonstrated excellent paragraphing skills and logical organization of information. Transitions between ideas were clear and effective.", "lexical_resource": "The candidate used a wide range of vocabulary accurately and appropriately. The vocabulary used was varied and precise.", "grammatical_range_accuracy": "The candidate accurately used a variety of complex grammatical structures with very few errors. Sentence structures were varied, and punctuation was used appropriately.", "band_scores": {"task_achievement": 9, "coherence_cohesion": 9, "lexical_resource": 9, "grammatical_range_accuracy": 8.5, "overall_band": 8.875}, "improved_response": "The graph presents the recycling rates of four distinct materials \\u2014 paper & cardboard, glass containers, aluminium cans, and plastics \\u2014 over the span of nearly three decades from 1982 to 2010. Paper and cardboard held the leading position in recycling rates, initiating at around 50% in 1982 and witnessing a consistent increase to nearly 80% by the year 2010. Glass containers followed a comparable upward trajectory, commencing at approximately 40% and escalating to 70% over the same period, signifying noteworthy progress. Aluminium cans also experienced an incremental rise in recycling rates, from a mere 10% in 1982 to just above 60% by 2010. In stark contrast, plastics remained at the rear with the lowest recycling rates. Back in 1982, only about 5% of plastics were recycled, and although this figure marginally increased annually, by 2010, the recycling rate of plastics was still a dismal 10%. In summary, while all materials demonstrated improvements in recycling rates, paper and cardboard continually held dominance, with plastics showing the least advancement.", "did_well": [], "could_improve": []}	2025-02-22 15:13:58.727053
22	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 15:28:07.866735
23	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 15:28:58.214548
24	1	1	Dear Richard,\n\nI hope you are doing well. Thank you for help me take care of my house and pet for I am on holiday. I really appreciate.\n\nIf you need contact me, you call me on +44 7123 456789 or email me at john.smith@email.com. I check my messages when I can.\n\nFor my dog, please feed her twice a day, in the morning and night. Her food is in kitchen. She also needs short walk every night. Please give fresh water all the time.\n\nI have some plants in the living room and on the balcony. They need water every week.\n\nThanks you for your help! I will bring you small gift from my trip.\n\nSee you soon,\nGavin	{"general_comment": "Error processing feedback.", "did_well": [], "could_improve": []}	2025-02-22 15:30:18.396925
25	1	23	Graf is pie like pizza.	{"task_achievement": "The candidate failed to address the prompt and did not summarize the key features of the graph. There were no comparisons made between the different buildings. The response does not meet the requirements of the task.", "coherence_cohesion": "The candidate\\u2019s response is not clear or logical, and it lacks structure. There are no cohesive devices or effective transitions between ideas.", "lexical_resource": "The vocabulary used by the candidate is extremely limited and not appropriate for the task.", "grammatical_range_accuracy": "The candidate's sentence structure is extremely simple and contains a spelling error ('Graf' instead of 'Graph').", "band_scores": {"task_achievement": 1.0, "coherence_cohesion": 1.0, "lexical_resource": 1.0, "grammatical_range_accuracy": 1.0, "overall_band": 1.0}, "improved_response": "The pie chart illustrates the cost distribution among five buildings labeled A, B, C, D, and E. It is noticeable that Building A incurred the most significant cost, with a share of 24.3%. This was closely followed by Building C, which accounted for 22% of the total cost. Building E was responsible for 20.1% of the costs, while Buildings D and B had lower shares of 16.4% and 17.2% respectively. The chart provides an insightful overview of how the costs were allocated across these five buildings during the given month.", "did_well": [], "could_improve": []}	2025-02-26 17:53:15.371479
26	1	1	I like house shiting	{"task_achievement": "The candidate's response doesn't meet the requirements of the task. The key features and relevant comparisons are not addressed.", "coherence_cohesion": "The response lacks coherence and cohesion since there's only one short sentence provided without context or logical structure.", "lexical_resource": "Limited vocabulary is used and the term 'house shiting' is not appropriate or clear in meaning.", "grammatical_range_accuracy": "Although there is no grammatical error in the sentence, the range is very limited with only one simple sentence provided.", "band_scores": {"task_achievement": 1.0, "coherence_cohesion": 1.0, "lexical_resource": 2.0, "grammatical_range_accuracy": 2.0, "overall_band": 1.5}, "improved_response": "I enjoy the process of relocating to a new house. The excitement of exploring a new neighborhood and setting up the home with personal touches truly makes the experience enjoyable for me.", "did_well": [], "could_improve": []}	2025-02-27 09:42:23.834892
\.


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gavinreid
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, false);


--
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gavinreid
--

SELECT pg_catalog.setval('public.tasks_id_seq', 30, true);


--
-- Name: transcripts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gavinreid
--

SELECT pg_catalog.setval('public.transcripts_id_seq', 26, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gavinreid
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- PostgreSQL database dump complete
--

