"""Add landing page analytics columns

Revision ID: 5c0b51f819a5
Revises: b40c0bbfb2af
Create Date: 2025-03-31 10:58:12.919713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0b51f819a5'
down_revision = 'b40c0bbfb2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_landing_page', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('converted_to_signup', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('referrer', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_analytics', schema=None) as batch_op:
        batch_op.drop_column('browser')
        batch_op.drop_column('device_type')
        batch_op.drop_column('referrer')
        batch_op.drop_column('converted_to_signup')
        batch_op.drop_column('is_landing_page')

    # ### end Alembic commands ###
