"""add demo analytics table

Revision ID: b40c0bbfb2af
Revises: 
Create Date: 2025-03-08 17:10:51.949239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40c0bbfb2af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('sections_viewed', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_analytics')
    # ### end Alembic commands ###
